apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-dotnet-basic-mtxweeje
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-dotnet-basic-mtxweeje 
  name: backend-tests-dotnet-basic-mtxweeje
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-dotnet-basic-mtxweeje 
